# Generated by Django 4.1.3 on 2022-11-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pelicula_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='Precio',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
