# Generated by Django 4.1.3 on 2022-11-25 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pelicula_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Ubicacion', models.CharField(max_length=50)),
                ('Pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pelicula')),
            ],
        ),
    ]
