# Generated by Django 4.1.3 on 2022-11-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_cine'),
    ]

    operations = [
        migrations.AddField(
            model_name='cine',
            name='Proyector',
            field=models.CharField(choices=[('Epson', 'Epson'), ('Canon', 'Canon'), ('Generic', 'Generic')], default='Epson', max_length=10),
        ),
    ]
