# Generated by Django 4.1.3 on 2022-11-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_cine_proyector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'permissions': [('Admin_generico', 'Puede: Editar y Crear Peliculas')]},
        ),
    ]
