# Generated by Django 4.1.3 on 2022-12-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_pelicula_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'permissions': [('Admin_generico', 'Puede: Editar y Crear Peliculas'), ('Membresia', 'Visualizar el detalle de las peliculas')]},
        ),
    ]
